export { default as HeroVisit } from "./visit/HeroVisit";
export { default as WhatIsThisPlace } from "./visit/WhatIsThisPlace";
export { default as KuriyamaPlan } from "./visit/KuriyamaPlan";
export { default as DayPassJapan } from "./visit/DayPassJapan";
export { default as Products } from "./visit/Products";
export { default as DailyPassBanner } from "./visit/DailyPassBanner";
export { default as VisitProcess } from "./visit/VisitProcess";
export { default as SeasonalActivities } from "./visit/SeasonalActivities";
export { default as Rules } from "./visit/Rules";
export { default as HorizontalGallery } from "./visit/HorizontalGallery";
export { default as DailyPass } from "./visit/DailyPass";
export { default as FAQ } from "./visit/FAQ";
export { default as Reviews } from "./Reviews";
export { default as Tariffs } from "./visit/Tariffs";
export { default as Footer } from "./Footer";
export { default as BeekeepingHero } from "./beekeeping/BeekeepingHero";
export { default as BeekeepingSlide2 } from "./beekeeping/BeekeepingSlide2";
export { default as BeekeepingSlide3 } from "./beekeeping/BeekeepingSlide3";
export { default as BeekeepingSlide4 } from "./beekeeping/BeekeepingSlide4";
export { default as BeekeepingSlide5 } from "./beekeeping/BeekeepingSlide5";
export { default as BeekeepingSlide6 } from "./beekeeping/BeekeepingSlide6";
export { default as BeekeepingClosing } from "./beekeeping/BeekeepingClosing";
export { default as PersonalBeekeepingHero } from "./personal-beekeeping/PersonalBeekeepingHero";
export { default as PersonalBeekeepingSlide2 } from "./personal-beekeeping/PersonalBeekeepingSlide2";
export { default as PersonalBeekeepingSlide3 } from "./personal-beekeeping/PersonalBeekeepingSlide3";
export { default as PersonalBeekeepingSlide4 } from "./personal-beekeeping/PersonalBeekeepingSlide4";
export { default as PersonalBeekeepingSlide5 } from "./personal-beekeeping/PersonalBeekeepingSlide5";
export { default as PersonalBeekeepingSlide6 } from "./personal-beekeeping/PersonalBeekeepingSlide6";
export { default as PersonalBeekeepingSlide7 } from "./personal-beekeeping/PersonalBeekeepingSlide7";
export { default as PersonalBeekeepingSlide8 } from "./personal-beekeeping/PersonalBeekeepingSlide8";
export { default as PersonalBeekeepingSlide9 } from "./personal-beekeeping/PersonalBeekeepingSlide9";
export { default as PersonalBeekeepingSlide10 } from "./personal-beekeeping/PersonalBeekeepingSlide10";
export { default as PersonalBeekeepingSlide11 } from "./personal-beekeeping/PersonalBeekeepingSlide11";
export { default as PersonalBeekeepingClosing } from "./personal-beekeeping/PersonalBeekeepingClosing";
export { default as ProductionHero } from "./production/ProductionHero";
export { default as ProductionSlide2 } from "./production/ProductionSlide2";
export { default as ProductionSlide3 } from "./production/ProductionSlide3";
export { default as ProductionSlide4 } from "./production/ProductionSlide4";
export { default as ProductionSlide5 } from "./production/ProductionSlide5";
export { default as ProductionSlide6 } from "./production/ProductionSlide6";
export { default as ConceptHero } from "./concept/ConceptHero";
export { default as ConceptSlide2 } from "./concept/ConceptSlide2";
export { default as ConceptSlide3 } from "./concept/ConceptSlide3";
export { default as ConceptSlide4 } from "./concept/ConceptSlide4";
export { default as ConceptSlide5 } from "./concept/ConceptSlide5";
export { default as ConceptSlide6 } from "./concept/ConceptSlide6";






export { default as ProductionSlide7 } from "./production/ProductionSlide7";
export { default as ProductionSlide8 } from "./production/ProductionSlide8";
export { default as CorporateBeekeepingHero } from "./corporate-beekeeping/CorporateBeekeepingHero";
export { default as CorporateBeekeepingSlide2 } from "./corporate-beekeeping/CorporateBeekeepingSlide2";
export { default as CorporateBeekeepingSlide3 } from "./corporate-beekeeping/CorporateBeekeepingSlide3";
export { default as CorporateBeekeepingSlide4 } from "./corporate-beekeeping/CorporateBeekeepingSlide4";
export { default as CorporateBeekeepingSlide5 } from "./corporate-beekeeping/CorporateBeekeepingSlide5";
export { default as CorporateBeekeepingSlide6 } from "./corporate-beekeeping/CorporateBeekeepingSlide6";

export { default as PolinationHero } from "./polination/PolinationHero";
export { default as PolinationSlide2 } from "./polination/PolinationSlide2";
export { default as PolinationSlide3 } from "./polination/PolinationSlide3";
export { default as PolinationSlide4 } from "./polination/PolinationSlide4";
export { default as PolinationSlide5 } from "./polination/PolinationSlide5";
export { default as PolinationSlide6 } from "./polination/PolinationSlide6";
export { default as PolinationSlide7 } from "./polination/PolinationSlide7";
export { default as PolinationSlide8 } from "./polination/PolinationSlide8";
export { default as PolinationSlide9 } from "./polination/PolinationSlide9";
export { default as PolinationSlide10 } from "./polination/PolinationSlide10";
export { default as CorporateBeekeepingSlide7 } from "./corporate-beekeeping/CorporateBeekeepingSlide7";
export { default as CorporateBeekeepingSlide8 } from "./corporate-beekeeping/CorporateBeekeepingSlide8";
export { default as CorporateBeekeepingSlide9 } from "./corporate-beekeeping/CorporateBeekeepingSlide9";
export { default as CorporateBeekeepingSlide10 } from "./corporate-beekeeping/CorporateBeekeepingSlide10";
export { default as CorporateBeekeepingSlide11 } from "./corporate-beekeeping/CorporateBeekeepingSlide11";
export { default as CorporateBeekeepingSlide12 } from "./corporate-beekeeping/CorporateBeekeepingSlide12";
export { default as CorporateBeekeepingClosing } from "./corporate-beekeeping/CorporateBeekeepingClosing";

export { default as PhotoVideoHero } from "./photo-video/PhotoVideoHero";
export { default as PhotoVideoSlide2 } from "./photo-video/PhotoVideoSlide2";
export { default as PhotoVideoSlide3 } from "./photo-video/PhotoVideoSlide3";
export { default as PhotoVideoSlide4 } from "./photo-video/PhotoVideoSlide4";
export { default as PhotoVideoSlide5 } from "./photo-video/PhotoVideoSlide5";
export { default as PhotoVideoSlide6 } from "./photo-video/PhotoVideoSlide6";
export { default as PhotoVideoSlide7 } from "./photo-video/PhotoVideoSlide7";
export { default as PhotoVideoSlide8 } from "./photo-video/PhotoVideoSlide8";
export { default as PhotoVideoSlide9 } from "./photo-video/PhotoVideoSlide9";
export { default as PhotoVideoClosing } from "./photo-video/PhotoVideoClosing";
